name: "Fonta Metric Collector"
on:
  schedule:
  - cron: "59 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ping Backend URL'
        run: curl -X POST 'https://fonta.vercel.app/api/metrics'
        
